# Connexion MySQL Student-Home
#addresse de la base de données MySQL Student-Home
db.url=jdbc:mysql://localhost:3306/student_home?useSSL=false&serverTimezone=Europe/Paris&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
# Ton identifiant MySQL
db.user=root

# Ton mot de passe MySQL student_home
db.password=